name: Update index.html in my nginx server inside the ec2 server

#This is the trigger
on: 
  push:
    branches:
      - main

#This is the actions to perform on those trigger
jobs:
  deploy-my-code:
    name: "Deploy my code to my nginx server"
    runs-on: ubuntu-latest #This is the runner provided by Github to run the following job
    env:
      SERVER_IP: ${{ vars.SERVER_IP }}

    steps:
      - uses: actions/checkout@v4 #it allows the actions in runner to chekout my code
        # with:
          # fetch-depth: 0 #Don't skip anything while fetching my code to the runner
      - name: "Configure SSH"
        run: |
          mkdir -p ~/.ssh 
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          cat ~/.ssh/config
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: "SSH KEY ACCESS"
        run: |
          touch myKey.pem 
          echo $SSH_KEY64 | base64 -d> mykey.pem && chmod 400 mykey.pem
          ssh-keygen -R $SERVER_IP
        env:
          SSH_KEY64: ${{ secrets.SSH_KEY64 }}

      - name: "Deploy the code to my server"
        run: |
          ssh -t ec2-user@SERVER_IP -i myKey.pem 'cd /var/www/html && git pull origin main'